function [X] = normal_generator(N,m1,m2)
    M = sqrt(2*pi/exp(1));
    new_N = N * ceil(M) * 2; %We generate N*M*2 uniform realizations
    U1 = uniform_generator(new_N,m1);
    % Random variable Y generated by inversion method
    Y = tan(U1*pi - pi/2);
    % Random variable X generated by acceptance-rejection method, X-normal(0,1)
    U2 = uniform_generator(new_N,m2);
    X = Y(U2 <=((1/sqrt(2*pi) * exp(-(Y.^2)/2))./(M/pi * 1./(1+Y.^2)) ));
    X = X(1:N);
end
