function [X] = normal_generator(N,m1,m2)
    N=100000;
    U1 = uniform_generator(N,m1);
    % Random variable Y generated by inversion method, g(y) = 1/pi * 1/(1+y^2)
    Y = tan(U1*pi - pi/2);
    % Random variable X generated by acceptance-rejection method, X-normal(0,1)
    M = sqrt(2*pi/exp(1));
    U2 = uniform_generator(N,m2);
    X = Y(U2 <=((1/sqrt(2*pi) * exp(-(Y.^2)/2))./(M/pi * 1./(1+Y.^2)) ));
end